language: php

php:
  - 7.0.8

before_install:
  - composer self-update
  - cd web
  - composer install
  - composer update

install:
  - cd web/core

notifications:
  email: false
  slack: ldso-italien:Q0U7sHHaNrawf6UVsV2J58A9
